<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<?php echo $this->getChildHtml('head') ?>
<link href="/vos/vos.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="/images/jquery.magnifier.js"></script>
 
</head>
<body>
<div id="outer">
	<div id="inner">
		<div id="head">
			
			<div id="navigation_bar">
			
				<?php include_once('vos/nav.php'); ?>
			
			</div>
		
		</div>
	
	<div id="left">
		<?php echo $this->getChildHtml('global_notices') ?> 
		<?php echo $this->getChildHtml('global_messages') ?>
		<?php echo $this->getChildHtml('content') ?> 
	
	<div id="bottom-left-caps">
	<img src="/images/caps/lh-caps-left.jpg" width =293px >
		<img src="/images/caps/lh-caps-right.jpg" width= 293px style="padding-left:6px;">
	</div>
	
	</div>
	
	<div id="right">
	
		<span class="logotitle">
			<img src="/images/headers/caps.png" width="425" height="218" border="0" usemap="#Map2" />
			<map name="Map2" id="Map2">
			<area shape="rect" coords="280,2,430,210" href="/homepage" />
			</map>
		</span>
		
		<div id="caps-right-text">
		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('capscategory')->toHtml(); ?>
		</div>
		
		<div id="caps-right-bottom">
		<img src="/images/caps/caps-right.jpg" width =193px style="padding-right:3px;">
		<img src="/images/caps/caps-left.jpg" width= 193px style="padding-left:3px;">
		</div>
	
	</div>
 <div class="vosfooter">
				<?php include_once('images/footer.php'); ?>	

	</div>
	 


</div>
	
</div>
<img id="larget" src="/images/bg/bg-xxl.jpg"  class="source-image"/>
</body>
</html>