<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<?php echo $this->getChildHtml('head') ?>
<link href="/vos/vos.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="/images/jquery.magnifier.js"></script>
</head>
<body>
	<div id="outer">
	
		<div id="inner">
			
			
			<div id="head">
			
			<div id="navigation_bar">
			
			<?php include_once('vos/nav.php'); ?>
			
			</div>
		
			</div>
			
			<div id="left">
					<?php echo $this->getChildHtml('global_notices') ?> 
					<?php echo $this->getChildHtml('global_messages') ?>
					<?php echo $this->getChildHtml('content') ?> 
				<span class="left-bottom">
				
				</span>
			</div>
			
			<div id="right">
			
					<span class="logotitle">
			<img src="/images/headers/blog.png" width="425" height="218" border="0" usemap="#Map2" />
			<map name="Map2" id="Map2">
			<area shape="rect" coords="280,2,430,210" href="/homepage" />
					</map>
					</span>
		
				<div id="blog-right-text">
					<span class="centre-offset">
					<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('blog')->toHtml(); ?>
					</span>
					
					<div class="blog-menu">
					
						<ul>
							<a href="/blog/category/team"><li>Team</li></a>
							<a href="/blog/category/events"><li>Events</li></a>
							<a href="/blog/category/products"><li>Products</li></a>
							<a href="/blog/category/other"><li>Other</li></a>
							<a href="/blog/"><li>All Posts</li></a>
						</ul>
					
					</div>
				</div>
				
				
			
			</div>
		 <div class="vosfooter">
				<?php include_once('images/footer.php'); ?>	

	</div>
			
			
		</div>	
		<div id="black-back" >
	</div>
<img id="larget" src="/images/bg/bg-xxl.jpg"  class="source-image"/>
</body>

</html>