<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<?php echo $this->getChildHtml('head') ?>
<link href="/vos/vos.css" rel="stylesheet" type="text/css" />
<link href="/vos/modal.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="outer">
	<div id="inner">
		<div id="head">
			
			<div id="navigation_bar">
			
					<?php include_once('vos/nav.php'); ?>
			
			</div>
		
		</div>
	
	<div id="left">
		<div class="posters">
		<span class="poster-left">	
			<span class="print_mouseover"><a href="/prints/happy-print.html"><img src="/images/prints/happy.jpg" height= 480px; ></a></span>
		</span>
	
		<span class="poster-middle">			
			<span class="print_mouseover"><a href="/prints/horns-print.html"><img src="/images/prints/grad.jpg" ></a></span>
			<span class="print_mouseover"><a href="/prints/crime.html"><img src="/images/prints/skull.jpg" ></a></span>
			<span class="print_mouseover"><a href="/prints/crime.html"><img src="/images/prints/not.jpg" ></a></span>
		</span>
	
		<span class="poster-right">
			<span class="print_mouseover"><a href="/prints/spine-print.html"><img src="/images/prints/spine.jpg" height= 480px;></a></span>
		</span>
	
	</div>
	</div>
	<div id="right">
	
		<span class="logotitle">
			<img src="/images/headers/prints.png" width="425" height="218" border="0" usemap="#Map2" />
			<map name="Map2" id="Map2">
			<area shape="rect" coords="280,2,430,210" href="/homepage" />
			</map>
		</span>
		
		<div id="caps-right-text">
		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('posterscategory')->toHtml(); ?>
		</div>
		
		<div id="posters-right-bottom">
		<img src="/images/prints/poster.png" >
		
		</div>
	
	</div>
  <div class="vosfooter">
				<?php include_once('images/footer.php'); ?>	

	</div>
	


</div>
	
</div>
<img id="larget" src="/images/bg/bg-xxl.jpg"  class="source-image"/>
</body>
</html>