<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!-- REMOVE BEFORE PRODUCTION ******* NO CACHING -->	
<meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
<meta http-equiv="Pragma" content="no-cache" />
<meta http-equiv="Expires" content="0" />



<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<link href="vos/style.css" rel="stylesheet" type="text/css" />
	 <script src="vos/js/jquery-2.1.1.min.js"></script>
	 <script src="vos/js/prefixfree.min.js"></script>
	 <script src="vos/js/picturefill.js"></script>
	 <script src="vos/js/matchmedia.js"></script>
	 <meta name="viewport" content="width=device-width, initial-scale=1.0"> 

	<script> <!-- 	 Responsive menu script -->	 
		 $(document).ready(function(){
		 $(".menu li a").each(function() {
		  if ($(this).next().length > 0) {
		   $(this).addClass("parent");
		  };
		 })
		 var menux = $('.menu li a.parent');
		 $( '<div class="more"><img src="img/btn-hamburger.png" alt=""></div>' ).insertBefore(menux);
		 $('.more').click(function(){
		   $(this).parent('li').toggleClass('open');
		 });
		 $('.menu-btn').click(function(){
		   $('nav').toggleClass('menu-open');
		 });
		 
		 $('.menu-button').click(function(){
		   $(this).parent('li').toggleClass('open');
		 });
		 });	
	 </script>

<!-- ADD COOKIE LAW SCRIPT BACK IN -->

</head>
<body>
<?php include_once('vos/inc/background.php'); ?> <!-- BACKGROUND IMAGE  -->
	<div class="outer">
			<div class="inner">
			<?php include_once('vos/inc/resp-nav.php'); ?> <!-- NAVIGATION -->
			<div class="page-wrap">
				<section class="main-content">
					<span class="primary-content">
					</span>
				</section>
			
				<aside class="main-sidebar">
					<span class="secondary-logo">
					<a href="/homepage"> <span data-picture data-alt="Vikings of Skate">
						<span data-src="img/headers/homepage.png"></span>
						<span data-src="img/headers/homepage.png" data-media="(min-width: 36.1em)"></span>
						<span data-src="img/headers/caps.png" data-media="(min-width: 65em)"></span>
						<span data-src="img/headers/caps.png" data-media="(min-width: 1000px)"></span>
					
						<!-- Fallback content for non-JS browsers. Same img src as the initial, unqualified source element. -->
						<noscript><img src="img/headers/caps.png" alt="Vikings of Skate"></noscript>
					</span></span>
					</a>					
					<div id="main-shirts" >
  <div >
    <div id="shirts-header">
    
    <?php 
	$product = Mage::registry('current_product');
	$categories = $product->getCategoryCollection();
	?>
	
	<?php 
	foreach($categories as $category) {
		if($category->getId() != 2) {
			$currentcatid = $category->getId();
			break;
		} 
	}
	?>
    
    <?php if($currentcatid == 3 /* T-SHIRTS */) {
	    echo '<img src="/images/headers/shirts.png" width="425" height="230" border="0" usemap="#Map2" />';
    } else {
	    echo '<img src="/images/products.png" width="425" height="230" border="0" usemap="#Map2" />';
    } ?>
 
      <map name="Map2" id="Map2">
         <area shape="rect" coords="280,2,430,210" href="/homepage" />
      </map>
    </div>
    <div style="padding-right:26px;"> <?php echo $this->getChildHtml('global_notices') ?> <?php echo $this->getChildHtml('global_messages') ?> <?php echo $this->getChildHtml('content') ?>
      <p align="justify" class="style1"><br />
      </p>
      <p class="style1"></p>
    </div>
  </div>
</div>
					
					
				</span>
				</aside> 
			
			</div><!-- close page wrap -->			
		<div class="footer"><a href="t&c.html">Copyright VOS 2014 - All Rights Reserved</a></div>
		</div>	
		</div>
</body>

</html>