<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!-- REMOVE BEFORE PRODUCTION ******* NO CACHING -->	
<meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
<meta http-equiv="Pragma" content="no-cache" />
<meta http-equiv="Expires" content="0" />



<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<link href="vos/style.css" rel="stylesheet" type="text/css" />
	 <script src="vos/js/jquery-2.1.1.min.js"></script>
	 <script src="vos/js/prefixfree.min.js"></script>
	 <script src="vos/js/picturefill.js"></script>
	 <script src="vos/js/matchmedia.js"></script>
	 <meta name="viewport" content="width=device-width, initial-scale=1.0"> 

	<script> <!-- 	 Responsive menu script -->	 
		 $(document).ready(function(){
		 $(".menu li a").each(function() {
		  if ($(this).next().length > 0) {
		   $(this).addClass("parent");
		  };
		 })
		 var menux = $('.menu li a.parent');
		 $( '<div class="more"><img src="img/btn-hamburger.png" alt=""></div>' ).insertBefore(menux);
		 $('.more').click(function(){
		   $(this).parent('li').toggleClass('open');
		 });
		 $('.menu-btn').click(function(){
		   $('nav').toggleClass('menu-open');
		 });
		 
		 $('.menu-button').click(function(){
		   $(this).parent('li').toggleClass('open');
		 });
		 });	
	 </script>

<!-- ADD COOKIE LAW SCRIPT BACK IN -->

</head>
<body>
<?php include_once('vos/inc/background.php'); ?> <!-- BACKGROUND IMAGE  -->
	<div class="outer">
			<div class="inner">
			<?php include_once('vos/inc/resp-nav.php'); ?> <!-- NAVIGATION -->
			<div class="page-wrap">
				<section class="main-content">
					<span class="primary-content">
						
						<div class="products">
							<div class="row-a">	
									<a href="http://www.vikingsofskate.com/shirts/broken-vos.html">
											<span data-picture data-alt="Vikings of Skate - White Broken Tee">
											<span data-src="img/products/shirts/broken-300.jpg"></span> 
											<span data-src="img/products/shirts/broken-300.jpg" data-media="(min-width: 400px)"></span>
											<span data-src="img/products/shirts/broken-600.jpg" data-media="(min-width: 1000px)"></span>
											<!-- Fallback content for non-JS browsers. Same img src as the initial, unqualified source element. -->
											<noscript><img src="img/products/shirts/broken-300.jpg" alt="Vikings of Skate - White Broken Tee"></noscript>
											</span></a>
									<a href="http://www.vikingsofskate.com/shirts/kids.html">
											<span data-picture data-alt="Vikings of Skate - Kids Tee">
											<span data-src="img/products/shirts/kids-300.jpg"></span> 
											<span data-src="img/products/shirts/kids-300.jpg" data-media="(min-width: 400px)"></span>
											<span data-src="img/products/shirts/kids-600.jpg" data-media="(min-width: 1000px)"></span>
											<!-- Fallback content for non-JS browsers. Same img src as the initial, unqualified source element. -->
											<noscript><img src="img/products/shirts/kids-300.jpg" alt="Vikings of Skate - Kids Tee"></noscript>
											</span></a>
									<a href="http://www.vikingsofskate.com/shirts/spine-vos.html">
											<span data-picture data-alt="Vikings of Skate - Spine Tee">
											<span data-src="img/products/shirts/spine-300.jpg"></span> 
											<span data-src="img/products/shirts/spine-300.jpg" data-media="(min-width: 400px)"></span>
											<span data-src="img/products/shirts/spine-600.jpg" data-media="(min-width: 1000px)"></span>
											<!-- Fallback content for non-JS browsers. Same img src as the initial, unqualified source element. -->
											<noscript><img src="img/products/shirts/spine-300.jpg" alt="Vikings of Skate - Kids Tee"></noscript>
											</span></a>
									<a href="http://www.vikingsofskate.com/shirts/happy-vos.html">
											<span data-picture data-alt="Vikings of Skate - Happy Tee">
											<span data-src="img/products/shirts/happy-300.jpg"></span> 
											<span data-src="img/products/shirts/happy-300.jpg" data-media="(min-width: 400px)"></span>
											<span data-src="img/products/shirts/happy-600.jpg" data-media="(min-width: 1000px)"></span>
											<!-- Fallback content for non-JS browsers. Same img src as the initial, unqualified source element. -->
											<noscript><img src="img/products/shirts/happy-300.jpg" alt="Vikings of Skate - Happy Tee"></noscript>
											</span></a>	
									<a href="http://www.vikingsofskate.com/shirts/fade.html">
											<span data-picture data-alt="Vikings of Skate - Fade Tee">
											<span data-src="img/products/shirts/grad-300.jpg"></span> 
											<span data-src="img/products/shirts/grad-300.jpg" data-media="(min-width: 400px)"></span>
											<span data-src="img/products/shirts/grad-600.jpg" data-media="(min-width: 1000px)"></span>
											<!-- Fallback content for non-JS browsers. Same img src as the initial, unqualified source element. -->
											<noscript><img src="img/products/shirts/grad-300.jpg" alt="Vikings of Skate - Fade Tee"></noscript>
											</span></a>
									<a href="http://www.vikingsofskate.com/shirts/vert.html">
											<span data-picture data-alt="Vikings of Skate - Vert Tee">
											<span data-src="img/products/shirts/vert-300.jpg"></span> 
											<span data-src="img/products/shirts/vert-300.jpg" data-media="(min-width: 400px)"></span>
											<span data-src="img/products/shirts/vert-600.jpg" data-media="(min-width: 1000px)"></span>
											<!-- Fallback content for non-JS browsers. Same img src as the initial, unqualified source element. -->
											<noscript><img src="img/products/shirts/vert-300.jpg" alt="Vikings of Skate - Vert Tee"></noscript>
											</span></a>		
			
							</div>
							<div class="row-b">	
									<a href="http://www.vikingsofskate.com/shirts/code-vos.html">
											<span data-picture data-alt="Vikings of Skate - Code Tee">
											<span data-src="img/products/shirts/code-300.jpg"></span> 
											<span data-src="img/products/shirts/code-300.jpg" data-media="(min-width: 400px)"></span>
											<span data-src="img/products/shirts/code-600.jpg" data-media="(min-width: 1000px)"></span>
											<!-- Fallback content for non-JS browsers. Same img src as the initial, unqualified source element. -->
											<noscript><img src="img/products/shirts/code-300.jpg" alt="Vikings of Skate - Code Tee"></noscript>
											</span></a>
									<a href="http://www.vikingsofskate.com/shirts/horns-vos.html">
											<span data-picture data-alt="Vikings of Skate - Horns Tee">
											<span data-src="img/products/shirts/horns-300.jpg"></span> 
											<span data-src="img/products/shirts/horns-300.jpg" data-media="(min-width: 400px)"></span>
											<span data-src="img/products/shirts/horns-600.jpg" data-media="(min-width: 1000px)"></span>
											<!-- Fallback content for non-JS browsers. Same img src as the initial, unqualified source element. -->
											<noscript><img src="img/products/shirts/horns-300.jpg" alt="Vikings of Skate - Horns Tee"></noscript>
											</span></a>
									<a href="http://www.vikingsofskate.com/shirts/rip-vos.html">
											<span data-picture data-alt="Vikings of Skate - RIP Tee">
											<span data-src="img/products/shirts/rip-300.jpg"></span> 
											<span data-src="img/products/shirts/rip-300.jpg" data-media="(min-width: 400px)"></span>
											<span data-src="img/products/shirts/rip-600.jpg" data-media="(min-width: 1000px)"></span>
											<!-- Fallback content for non-JS browsers. Same img src as the initial, unqualified source element. -->
											<noscript><img src="img/products/shirts/rip-300.jpg" alt="Vikings of Skate - RIP Tee"></noscript>
											</span></a>					
									<a href="http://www.vikingsofskate.com/shirts/raglan.html">
											<span data-picture data-alt="Vikings of Skate - Raglan Tee">
											<span data-src="img/products/shirts/raglan-300.jpg"></span> 
											<span data-src="img/products/shirts/raglan-300.jpg" data-media="(min-width: 400px)"></span>
											<span data-src="img/products/shirts/raglan-600.jpg" data-media="(min-width: 1000px)"></span>
											<!-- Fallback content for non-JS browsers. Same img src as the initial, unqualified source element. -->
											<noscript><img src="img/products/shirts/raglan-300.jpg" alt="Vikings of Skate - Raglan Tee"></noscript>
											</span></a>	
									<a href="http://www.vikingsofskate.com/shirts/notskateboarding.html">
											<span data-picture data-alt="Vikings of Skate - NOT Tee">
											<span data-src="img/products/shirts/not-300.jpg"></span> 
											<span data-src="img/products/shirts/not-300.jpg" data-media="(min-width: 400px)"></span>
											<span data-src="img/products/shirts/not-600.jpg" data-media="(min-width: 1000px)"></span>
											<!-- Fallback content for non-JS browsers. Same img src as the initial, unqualified source element. -->
											<noscript><img src="img/products/shirts/not-300.jpg" alt="Vikings of Skate - Vert Tee"></noscript>
											</span></a>	
									<a href="http://www.vikingsofskate.com/shirts/ollie-vos.html">
											<span data-picture data-alt="Vikings of Skate - Olly Tee">
											<span data-src="img/products/shirts/olly-300.jpg"></span> 
											<span data-src="img/products/shirts/olly-300.jpg" data-media="(min-width: 400px)"></span>
											<span data-src="img/products/shirts/olly-600.jpg" data-media="(min-width: 1000px)"></span>
											<!-- Fallback content for non-JS browsers. Same img src as the initial, unqualified source element. -->
											<noscript><img src="img/products/shirts/olly-300.jpg" alt="Vikings of Skate - Olly Tee"></noscript>
											</span></a>	
							</div>
					</span>
				</section>
			
				<aside class="main-sidebar">
					<span class="secondary-logo">
					<a href="/homepage"> <span data-picture data-alt="Vikings of Skate">
						<span data-src="img/headers/homepage.png"></span>
						<span data-src="img/headers/homepage.png" data-media="(min-width: 36.1em)"></span>
						<span data-src="img/headers/shirts.png" data-media="(min-width: 58em)"></span>
						<span data-src="img/headers/shirts.png" data-media="(min-width: 1000px)"></span>
					
						<!-- Fallback content for non-JS browsers. Same img src as the initial, unqualified source element. -->
						<noscript><img src="img/headers/summer2014.png" alt="Vikings of Skate"></noscript>
					</span></span>
					</a>					
					<div class="secondary-text">
					<p>All VOS shirts are 100% cotton and printed lovingly by experts. Your VOS shirt will last a long time as long as you take proper care of it. Wash at 30 degrees, iron inside out. Don’t dry in direct sun light. Wash dark colours separately.</p>
					</div>
					
					<div class="right-bottom-shirts">
					<img src="/images/shirts/screenLogo.jpg" >
					<img src="/images/shirts/yellowVirgin.jpg">
					</div>
				</span>
				</aside> 
			
			</div><!-- close page wrap -->			
		<div class="footer"><a href="t&c.html">Copyright VOS 2014 - All Rights Reserved</a></div>
		</div>	
		</div>
</body>

</html>