<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!-- REMOVE BEFORE PRODUCTION ******* NO CACHING -->	
<meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
<meta http-equiv="Pragma" content="no-cache" />
<meta http-equiv="Expires" content="0" />

<meta name="robots" content="INDEX,FOLLOW" />
<link rel="icon" href="/images/fav.png" type="image/x-icon" />
<link rel="shortcut icon" href="/images/fav.png" type="image/x-icon" />

<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<link href="vos/style.css" rel="stylesheet" type="text/css" />
	 <script src="vos/js/jquery-2.1.1.min.js"></script>
	 <script src="vos/js/prefixfree.min.js"></script>
	 <script src="vos/js/picturefill.js"></script>
	 <script src="vos/js/matchmedia.js"></script>
	 <meta name="viewport" content="width=device-width, initial-scale=1.0"> 

	<script> <!-- 	 Responsive menu script -->	 
		 $(document).ready(function(){
		 $(".menu li a").each(function() {
		  if ($(this).next().length > 0) {
		   $(this).addClass("parent");
		  };
		 })
		 var menux = $('.menu li a.parent');
		 $( '<div class="more"><img src="img/btn-hamburger.png" alt=""></div>' ).insertBefore(menux);
		 $('.more').click(function(){
		   $(this).parent('li').toggleClass('open');
		 });
		 $('.menu-btn').click(function(){
		   $('nav').toggleClass('menu-open');
		 });
		 
		 $('.menu-button').click(function(){
		   $(this).parent('li').toggleClass('open');
		 });
		 });	
	 </script>

<!-- ADD COOKIE LAW SCRIPT BACK IN -->

</head>
<body>
<?php include_once('vos/inc/background.php'); ?> <!-- BACKGROUND IMAGE  -->
	<div class="outer">
			<div class="inner">
			<?php include_once('vos/inc/resp-nav.php'); ?> <!-- NAVIGATION -->
			<div class="page-wrap">
				<section class="main-content">
					<span class="primary-content">
						<div class="secondary-text">
				  <div class='container'>
  <div class='col4'>
    <div class='image'>
      <img alt='Ben Broyd - Vikings of Skate' height='213' src='/images/team/ben_colour_325.jpg' width='320'>
    </div>
    <div class='copy'>
      <h3>Ben Broyd</h3>
      <p>Ben was spotted ripping it up at the
	            London Ledge show last summer.
	            He's originally from London but now
	            studying music at Sheffield University. </p>
	         <p>He pretty much spends all his time
	            chilling, skating and making music.
				He's 19 and been skating for 6 years
				now, his favourite parks are Stockwell
				(brixton beach) or Kimber mini.
				Ben just loves to find a new bowl to
				skate.</p><p>Checkout his films on our
				Youtube channel.</p>
      
    </div>
    <div class='clear'></div>
  </div>
  <div class='col4'>
    <div class='image'>
      <img alt='Kai Hardy - Vikings of Skate' height='213' src='/images/team/kai_325px_colour.jpg' width='320'>
    </div>
    <div class='copy'>
      <h3>Kai Hardy</h3>
      <p>
           	Kai got his first skateboard at just
           	three years old. He skates Stafford 
           	bowl and Stoke Plaza a lot. The Rubicon 
           	skate camp is a favourite, he's also
           	been skating with Kris Vile of Vans,
           	Santa Cruz and Volcom. Kris wants to
           	skate the new Level with him.</p>
        <p>	Another favourite is the Rapmz indoor
           	park in Cannock, Staffs. He likes all 
           	terrain and even skates with a broom 
           	sweeping up the leaves. He's a big fan 
           	of  Aaron 'jaws' Homoki, Mike Mo Capaldi, 
           	Sean Malto and the Creature team he
           	met at the Shoreham bowl.
            </p>
     
    </div>
    <div class='clear'></div>
  </div>
  <div class='col4'>
    <div class='image'>
      <img alt='Harry Phelps - Vikings of Skate' height='213' src='/images/team/harry_colour_325.jpg' width='320'>
    </div>
    <div class='copy'>
      <h3>Harry Phelps</h3>
      <p>Harry Phelps is currently the ranked No1 UK slalom racer by the ISSA and just lives to skate.
                	5 years into it - street, slalom, 
                	downhill but bowls are the favourite.
                	He travels all over the country to find
                	the best spots but he's from Crawley.
                	Harry enters lots of comps, one in 
                	particular was pretty cool - a slide
                	comp at Brands Hatch against older 
                	guys from all over the UK 
                	Harry won it of course.</p> 
                	<p>He listens to rock, ska and old school
                	reggae.
                	He attacks all terrain and wants
                	to keep pushing himself to the limit.</p>
      
    </div>
    <div class='clear'></div>
  </div>
    <div class='col4'>
    <div class='image'>
      <img alt='Amir Williams - Vikings of Skate' height='213' src='/images/team/amir_colour_325.jpg' width='320'>
    </div>
    <div class='copy'>
      <h3>Amir Williams</h3>
      <p>
            Amir's been in Brighton all his life
            and started skating the Level at 17.
            Back then he used his job seekers
            allowance to skate new terrain with  
			new skaters. He was spotted early on 
			and has several sponsors including 
			Etnies, Alis, Gumball, Route One 
			and he has a few Pariah tours
		 	under his belt. </p><p>
			Amir flys abroad a lot to skate, 
			his favourite spots are in Denmark 
			and Spain.
			He's an original Level skater 
			and although it was his lifeblood he's
			ripping it up at the new Level.</p>
      
    </div>
    <div class='clear'></div>
  </div>
    <div class='col4'>
    <div class='image'>
      <img alt='Nathan McNeil - Vikings of Skate' height='213' src='/images/team/nathan_325px_colour.jpg' width='320'>
    </div>
    <div class='copy'>
      <h3>Nathan McNeil</h3>
      <p>
            Nathan's been skating for three years
			and already has loads of style.
			He mostly prefers to skate in Shoreham,
			Lewes, Woodingdean and Hollingdean
			but he just loves the new Level
			skatepark in Brighton.</p> <p>When he's not 
			out there skating Nathan mostly hangs
			out with his girlfriend and mates and
			listens to hip hop.
			He can't wait for a Vikings of Skate
			deck one day.

            </p>
      
    </div>
    <div class='clear'></div>
  </div>
    <div class='col4'>
    <div class='image'>
      <img alt='Jesse Thomas - Vikings of Skate' height='213' src='/img/team/jesse_325px_colour.jpg' width='320'>
    </div>
    <div class='copy'>
      <h3>Jesse Thomas - Vikings of Skate</h3>
      <p>
           			Originally from Lincoln Jesse can often
           			be found skating in Brighton and it's
           			usually vert - any sort! He loves a 
           			really crazy challenge. 
           			His favourite skate spot is Malmo.
            	 	Jesse can't remember what got 
            		him into skating but he says he skates 
            		better than he walks:) </p>
            		<p>Last summer Jesse joined us at the London Ledge Show and ripped up the ramps,
we also met Ben there. Jesse's favourite skater is Caballero and his music choice 
is usually Metallica or Judas Priest.</p>
      
    </div>
    <div class='clear'></div>
  </div>
</div>
			</div>
					</span>
				</section>
			
				<aside class="main-sidebar">
					<div class="secondary-logo">
						<a href="/homepage"> <span data-picture data-alt="Vikings of Skate">
							<span data-src="img/headers/homepage.png"></span>
							<span data-src="img/headers/homepage.png" data-media="(min-width: 36.1em)"></span>
							<span data-src="img/headers/team2014.png" data-media="(min-width: 65em)"></span>
							<span data-src="img/headers/team2014.png" data-media="(min-width: 1000px)"></span>
					
						<!-- Fallback content for non-JS browsers. Same img src as the initial, unqualified source element. -->
							<noscript><img src="img/headers/team2014.png" alt="Vikings of Skate"></noscript>
							</span></span>
						</a>
						
					</div>
					<div class="secondary-text">
						
					</div>	 
				</aside> 
			
			</div><!-- close page wrap -->			
		<div class="inner">
		<div class="page-wrap">
		<div class="footer"><a href="t&c.html">Copyright VOS 2014 - All Rights Reserved</a></div>
		</div>
		</div>
		</div>	
		</div>
</body>

</html>