<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<?php echo $this->getChildHtml('head') ?>
<link href="/vos/vos.css" rel="stylesheet" type="text/css" />
<link href="/vos/modal.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="/images/jquery.magnifier.js"></script>

</head>
<body>
<div id="outer">


	<div id="inner">
		<div id="header">
			<div id="navigation_bar">
			<?php include_once('vos/nav.php'); ?>
			</div>
		</div>
		
		<span class="team-top-left">
			<a></a>
			</span>
			
		<span class="team-top-right">
			
				<span class="logotitle">
					<img src="/images/headers/team2013.png" width="425" height="215" border="0" usemap="#Map2" />
					<map name="Map2" id="Map2">
					<area shape="rect" coords="280,2,430,210" href="/about" />
					</map>
				</span>
			</span>
			
			<div id="team-bottom">
			
				<div class="team-ben">
					<span class="thumb-image">
						<a href="#ben_p"id="ben"><img onmouseover="this.src='/images/team/ben_colour_325.jpg'" alt="Ben Broyd" height="150" width="150" onmouseout="this.src='/images/team/benbroyd.png'" border="0" src="/images/team/benbroyd.png" alt="Ben" ><h3><span>Ben Broyd</span></h3></a>			
					</span>
				</div>
				
				<div class="team-kai">
					<span class="thumb-image">
						<a href="#kai_p"id="kai"><img onmouseover="this.src='/images/team/kai_325px_colour.jpg'" alt="Kai" height="150" width="150" onmouseout="this.src='/images/team/kai.png'" border="0" src="/images/team/kai.png" alt="Kai" ><h3><span>Kai Hardy</span></h3></a>			
					</span>
				</div>	
				
				<div class="team-harry">
					<span class="thumb-image">
						<a href="#harry_p"id="harryp"><img onmouseover="this.src='/images/team/harry_colour_325.jpg'" alt="Harry Phelps" height="150" width="150" onmouseout="this.src='/images/team/harryphelps.png'" border="0" src="/images/team/harryphelps.png" alt="Harry Phelps" ><h3><span>Harry Phelps</span></h3></a>
					</span>
				</div>	
				
				<div class="team-amir">
					<span class="thumb-image">
						<a href="#amir_p"id="amir"><img onmouseover="this.src='/images/team/amir_colour_325.jpg'" alt="Amir Williams" height="150" width="150" onmouseout="this.src='/images/team/amirwilliams.png'" border="0" src="/images/team/amirwilliams.png" alt="Amir Williams" ><h3><span>Amir Williams</span></h3></a>
					</span>
				</div>	
				
				<div class="team-nathan">
					<span class="thumb-image">
						<a href="#nathan_p"id="nathan"><img onmouseover="this.src='/images/team/nathan_325px_colour.jpg'" alt="Nathan" height="150" width="150" onmouseout="this.src='/images/team/nathan.png'" border="0" src="/images/team/nathan.png" alt="Nathan" ><h3><span>Nathan McNeill</span></h3></a>
					</span>
				</div>	
				
				<div class="team-jesse">
					<span class="thumb-image">
						<a href="#jessie_p"id="jessie"><img onmouseover="this.src='/images/team/jesse_325px_colour.jpg'" alt="Jesse" height="150" width="150" onmouseout="this.src='/images/team/jesse.png'" border="0" src="/images/team/jesse.png" alt="Jesse" ><h3><span>Jesse Thomas</span></h3></a>
					</span>
				</div>	
					
			</div>
	
		<!-- ben Team popup  -->
        <a href="#x" class="overlay" id="ben_p"></a>
        	 <div class="ben">
	            <a href="#x" class="close-modal">
	            <img src="/images/team/ben_colour_325.jpg" alt="jesse" width="325" height="325">
	            <div class="ben-bg">
	            <p>Ben was spotted ripping it up at the
	            London Ledge show last summer.
	            He's originally from London but now
	            studying music at Sheffield University. </p>
	         <p>He pretty much spends all his time
	            chilling, skating and making music.
				He's 19 and been skating for 6 years
				now, his favourite parks are Stockwell
				(brixton beach) or Kimber mini.
				Ben just loves to find a new bowl to
				skate.</p><p>Checkout his films on our
				Youtube channel.</p>
            	</a>
            	</div>
        	</div>
	<!-- end of ben pop up -->
	
	<!-- Kai Team popup  -->
        <a href="#x" class="overlay" id="kai_p"></a>
       
        	 <div class="kai">
            <a href="#x" class="close-modal">
            <img src="/images/team/kai_325px_colour.jpg" alt="Kai" width="325" height="325">
            <div class="kai-bg">
           
            <p>
           	Kai got his first skateboard at just
           	three years old. He skates Stafford 
           	bowl and Stoke Plaza a lot. The Rubicon 
           	skate camp is a favourite, he's also
           	been skating with Kris Vile of Vans,
           	Santa Cruz and Volcom. Kris wants to
           	skate the new Level with him.</p>
        <p>	Another favourite is the Rapmz indoor
           	park in Cannock, Staffs. He likes all 
           	terrain and even skates with a broom 
           	sweeping up the leaves. He's a big fan 
           	of  Aaron 'jaws' Homoki, Mike Mo Capaldi, 
           	Sean Malto and the Creature team he
           	met at the Shoreham bowl.
            </p>
             </a>
            </div>
        </div>
	<!-- end of kai pop up -->	
	
		<!-- HARRY P Team popup  -->
        <a href="#x" class="overlay" id="harry_p"></a>
        	 <div class="harry">
        	 <a href="#x" class="close-modal">
                <img src="/images/team/harry_colour_325.jpg" alt="Harry Phelps" width="325" height="325">
            	<div class="harryp-bg">
                	<p>Harry Phelps is currently the ranked No1 UK slalom racer by the ISSA and just lives to skate.
                	5 years into it - street, slalom, 
                	downhill but bowls are the favourite.
                	He travels all over the country to find
                	the best spots but he's from Crawley.
                	Harry enters lots of comps, one in 
                	particular was pretty cool - a slide
                	comp at Brands Hatch against older 
                	guys from all over the UK 
                	Harry won it of course.</p> 
                	<p>He listens to rock, ska and old school
                	reggae.
                	He attacks all terrain and wants
                	to keep pushing himself to the limit.</p>
            		</a>
            	</div>
			</div>        
        <!--end of Harry popup-->
        
        <!-- Amir Team popup  -->
        <a href="#x" class="overlay" id="amir_p"></a>
       
        	 <div class="amir">
            <a href="#x" class="close-modal">
            <img src="/images/team/amir_colour_325.jpg" alt="Amir Williams" width="325" height="325">
            <div class="amir-bg">
           
            <p>
            Amir's been in Brighton all his life
            and started skating the Level at 17.
            Back then he used his job seekers
            allowance to skate new terrain with  
			new skaters. He was spotted early on 
			and has several sponsors including 
			Etnies, Alis, Gumball, Route One 
			and he has a few Pariah tours
		 	under his belt. </p><p>
			Amir flys abroad a lot to skate, 
			his favourite spots are in Denmark 
			and Spain.
			He's an original Level skater 
			and although it was his lifeblood he's
			ripping it up at the new Level.</p>
            
        

            </a>
            </div>
        </div>
	<!-- end of amir pop up -->
     
     <!-- Nathan Team popup  -->
        <a href="#x" class="overlay" id="nathan_p"></a>
        	 <div class="nathan">
        	 <a href="#x" class="close-modal">
            <img src="/images/team/nathan_325px_colour.jpg" alt="Nathan McNeill" width="325" height="325">
            <div class="nathan-bg">
           
            <p>
            Nathan's been skating for three years
			and already has loads of style.
			He mostly prefers to skate in Shoreham,
			Lewes, Woodingdean and Hollingdean
			but he just loves the new Level
			skatepark in Brighton.</p> <p>When he's not 
			out there skating Nathan mostly hangs
			out with his girlfriend and mates and
			listens to hip hop.
			He can't wait for a Vikings of Skate
			deck one day.

            </p>
            
        

            </a>
            </div>
        </div>
	<!-- end of Nathan pop up -->
     
        <!-- jesse Team popup  -->
        <a href="#x" class="overlay" id="jessie_p"></a>
        	 <div class="jessie">
        	 <a href="#x" class="close-modal">
	            <img src="/images/team/jesse_325px_colour.jpg" alt="jesse" width="325" height="325">
           		<div class="jessie-bg">
           			<p>
           			Originally from Lincoln Jesse can often
           			be found skating in Brighton and it's
           			usually vert - any sort! He loves a 
           			really crazy challenge. 
           			His favourite skate spot is Malmo.
            	 	Jesse can't remember what got 
            		him into skating but he says he skates 
            		better than he walks:) </p>
            		<p>Last summer Jesse joined us at the London Ledge Show and ripped up the ramps,
we also met Ben there. Jesse's favourite skater is Caballero and his music choice 
is usually Metallica or Judas Priest.</p>
            		</a>
            	</div>
        	</div>
	<!-- end of jessie pop up -->
	

	
	
		
		
		
	
		
	</span>
 
		<div class="vosfooter">
			<?php include_once('images/footer.php'); ?>	
		</div>
	</div>
 		
</div>
<!--  -->
<!--  BACKGROUND IMAGE ROTATOR  -->
<!-- <div class="rotator" id="bgimgdiv"> 
<img src="/images/backgrounds/retouched-2.jpg"  class="source-image" alt=""/>
<img src="/images/backgrounds/retouched-4.jpg"  class="source-image" alt=""/>
<img src="/images/backgrounds/retouched-1.jpg"  class="source-image" alt=""/>  
<img src="/skin/frontend/default/default/images/images/backgrounds/voschk.jpg" class="source-image" alt=""/>  -->
<!-- END OF IMAGE ROTATOR  -->

</div>
<img id="larget" src="/images/bg/bg-xxl.jpg"  class="source-image"/>
</body>
</html>