<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<?php echo $this->getChildHtml('head') ?>
<link href="/vos/vos.css" rel="stylesheet" type="text/css" />
</head>

<body>

	<div id="outer">
		<div id="inner">
			<div id="header">
				<div id="navigation_bar">
					<?php include_once('vos/nav.php'); ?>
				</div>
			</div>
			
			<div id="main" >
				<div id="tnt-right-col">
        			<div id="logotitle"><img src="images/headers/tnt.png" width="425" height="215" border="0" usemap="#Map2" />
						<map name="Map2" id="Map2"> <area shape="rect" coords="280,2,430,210" href="/homepage" /></map>
					</div>
         		</div>
         		<div id="tntright">
					<?php echo $this->getChildHtml('global_messages') ?>
					<?php echo $this->getChildHtml('content') ?>           
		    	</div>	
  			</div>
		<div class="vosfooter">
		<?php include_once('images/footer.php'); ?>
		</div>
	</div>

<img id="larget" src="images/backgrounds/retouched-4.jpg"  class="source-image"/>

</body>
</html>
