<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<?php echo $this->getChildHtml('head') ?>
<link href="/images/vostpl.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="/images/jquery.magnifier.js"></script>
 
</head>
<body>
<div id="outer">


	<div id="inner">
		<div id="header">
			<div id="navigation_bar">
			<span class="nav_vos" > 
				
					<ul>
							
						<li><a href="#">PRODUCTS</a>	
								<ul>
									<li><a href="/shirts">SHIRTS</a></li>
									<li><a href="/caps">CAPS</a></li>
									<li><a href="/prints">SCREEN PRINTS</a></li>
								</ul>
						</li>
						
						<li><a href="/about">ABOUT</a></li>
						<li><a href="/team">TEAM</a></li>
						<li><a href="/this-and-that">THIS&amp;THAT</a></li>
						<li><a href="/ipad-app">IPAD APP</a></li>
					
					</ul>
				
			</span>
			
			<span class="vos-social-buttons">
				<a href="http://www.facebook.com/pages/Vikings-Of-Skate/160887060630674/" target="_blank">
				<img onmouseover="this.src='/images/icons/social/facebook-rollover.png'"  height="20" width="20" onmouseout="this.src='images/icons/social/facebook.png'" border="0" src="/images/icons/social/facebook.png" alt="Facebook" /></a>
				<a href="http://twitter.com/vikingsofskate/" target="_blank">
				<img onmouseover="this.src='/images/icons/social/twitter-rollover.png'" height="20" width="20" onmouseout="this.src='images/icons/social/twitter.png'" border="0" src="/images/icons/social/twitter.png" alt="Twitter" /></a>
				<a href="http://pinterest.com/vikingsofskate/" target="_blank">
				<img onmouseover="this.src='/images/icons/social/pinterest-rollover.png'"  height="20" width="20" onmouseout="this.src='images/icons/social/pinterest.png'" border="0" src="/images/icons/social/pinterest.png" alt="Pinterest" /></a>
				<a href="http://instagram.com/vikingsofskate/" target="_blank">
				<img onmouseover="this.src='/images/icons/social/instagram-rollover.png'"  height="20" width="20" onmouseout="this.src='images/icons/social/instagram.png'" border="0" src="/images/icons/social/instagram.png" alt="Instagram" /></a>
				<a href="http://vikingsofskate.tumblr.com/" target="_blank">
				<img onmouseover="this.src='/images/icons/social/tumblr-rollover.png'"  height="20" width="20" onmouseout="this.src='images/icons/social/tumblr.png'" border="0" src="/images/icons/social/tumblr.png" alt="Tumblr" /></a>
				
			</span>
		
			<span class="nav-right" >
			
						<ul>
							<li><a href="/checkout/cart/">CART</a></li>
							<li><a href="/checkout">CHECKOUT</a></li>
						</ul>
			
			</span>
			
			</div>
		
		</div>
			
	<span class="content-left">
		<?php echo $this->getChildHtml('global_notices') ?> 
		<?php echo $this->getChildHtml('global_messages') ?>
		<?php echo $this->getChildHtml('content') ?> 
	</span>
	
	<span class="content-right">
	
		<span class="logotitle">
			<img src="/images/headers/fall2014.png" width="425" height="218" border="0" usemap="#Map2" />
			<map name="Map2" id="Map2">
			<area shape="rect" coords="280,2,430,210" href="/about" />
			</map>
		</span>
		<span class="content-right-content">
		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('vosfront')->toHtml(); ?>
		</span>
		
	</span>
 
	<?php include_once('images/footer.php'); ?>	
	
	</div>
	 
<div id="black-back" > <!-- Background DIM effect - inline CSS removed and moved to vostpl.css -->

</div>

</body>
</html>