<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<?php echo $this->getChildHtml('head') ?>
<link href="/vos/vos.css" rel="stylesheet" type="text/css" />

</head>

<body>

	<div id="outer">
	
		<div id="inner">
			<div id="header">
				<div id="navigation_bar">
					<?php include_once('vos/nav.php'); ?>
				</div>	
			</div>
	

<div id="left">
<img id="larget" src=""  class="caps-image" width="586"/>
</div>


<div id="right">
  <div id="shirts-right-col">
    
    <div id="shirts-right""> 
    
    <div style="display:none; z-index:9999; position:absolute; top:345px; right:186px; height:140px; width:211px; background:url('/images/shad.png') no-repeat bottom right;" id="popmail">
  <div style="height:113px; width:182px; padding:6px; background:#FFF;">
  <table style="font-size:11px; clear:both;">
    <tr>
      <td>To&nbsp;</td>
      <td><input id="xemailadd" style="border:1px #000 solid; margin-bottom:2px; width:146px;" type="text" /></td>
    </tr>
    <tr>
      <td>From&nbsp;</td>
      <td><input id="email_from_id" style="border:1px #000 solid; width:146px; margin-bottom:2px;" type="text" /></td>
    </tr>
    <tr>
      <td>Note&nbsp;</td>
      <td><textarea id="email_note" style="border:1px #000 solid; width:141px; height:30px;" > </textarea></td>
    </tr>
  </table>
  <div style="clear:both;"><a href="javascript:" class="esend" onclick="mfrd();">&nbsp;</a><img style="cursor:pointer; float:right; padding-top:6px;" onclick="popsend(0);" src="/images/close.gif" width="20" /></div>
</div>
</div>

<div id="main-shirts" >

    <div id="caps-header">
	
    <span class="logotitle">
   		<img src="/images/headers/prints.png" width="425" height="218" border="0" usemap="#Map2" />';
    
 
      <map name="Map2" id="Map2">
         <area shape="rect" coords="280,2,430,210" href="/homepage" />
      </map>
     </span>
    </div>
    <div style="padding-right:26px;"> 
	

	<?php echo $this->getChildHtml('content') ?>
      	<p align="justify" class="style1"><br /></p>
      	<p class="style1"></p>
    </div>
  
</div>

   
    </div>
  </div>
</div>


	</div>

</div>


    
<div class="vosfooter">
<?php include_once('images/footer.php'); ?>
</div>
<img id="larget" src="/images/bg/bg-xxl.jpg"  class="source-image"/>

</body></html>