<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<?php echo $this->getChildHtml('head') ?>
<link href="/images/vostpl.css" rel="stylesheet" type="text/css" />
<script type="text/javascript"> function pro(flg){ if(flg==1){document.getElementById("nav_pro").src="/images/menu/products-rollover.png";}else{document.getElementById("nav_pro").src="/images/menu/products.png";} }
function abt(flg){ if(flg==1){document.getElementById("nav_about").src="/images/menu/about-rollover.png";}else{document.getElementById("nav_about").src="/images/menu/about.png";} }
function tnt(flg){ if(flg==1){document.getElementById("nav_tnt").src="/images/menu/thisthat-rollover.png";}else{document.getElementById("nav_tnt").src="/images/menu/thisthat.png";} }
function ctn(flg){ if(flg==1){document.getElementById("nav_ctn").src="/images/menu/contact-rollover.png";}else{document.getElementById("nav_ctn").src="/images/menu/contact.png";} }
</script>
<script type="text/javascript" src="/images/jquery.cycle.lite.min.js"></script>
<style type="text/css"> 
.rotator img{  width:100%; z-index:1; left:0; top:0; position:absolute;}
</style>
</head>
<body>

<?php echo $this->getChildHtml('sociallinks');?>

<div style="visibility:hidden; display:none;"> 
<img src="/images/backgrounds/retouched-2.jpg" alt="vos" />
<img src="/images/backgrounds/retouched-4.jpg" alt="vos" />
<img src="/images/backgrounds/retouched-1.jpg" alt="vos" />
<img src="/skin/frontend/default/default/images/images/backgrounds/voschk.jpg" alt="vos" /> 
</div>

<div id="nav_vos" ><a href="/products"><img id="nav_pro" onmouseout="pro(0)" onmouseover="pro(1);" src="/images/menu/products.png" alt="PRODUCTS" /></a> <a href="/about"><img id="nav_about" onmouseout="abt(0)" onmouseover="abt(1);" src="/images/menu/about.png" alt="ABOUT" /></a> <a href="/this-and-that"><img id="nav_tnt" onmouseout="tnt(0)" onmouseover="tnt(1);" src="/images/menu/thisthat.png" alt="THISandTHAT" /></a> <a href="/contact"><img id="nav_ctn" onmouseout="ctn(0)" onmouseover="ctn(1);" src="/images/menu/contact.png" alt="CONTACT" /></a></div>
<div id="navright" > 
  <script type="text/javascript"> function bk(bkv){ if(bkv){document.getElementById("idbk").src="/images/bkb.png"; }else{document.getElementById("idbk").src="/images/bkw.png";}}
function ck(ckv){ if(ckv){document.getElementById("idck").src="/images/ckb.png"; }else{document.getElementById("idck").src="/images/ckw.png";}}
 </script> 
  <a href="/checkout/cart/" ><img height="18" onmouseover="bk(1)" onmouseout="bk(0)" id="idbk" src="/images/bkw.png" alt="" /></a> <a href="/checkout"><img height="18" onmouseover="ck(1)" onmouseout="ck(0)" id="idck" src="/images/ckw.png" alt="" /></a> </div>
<div id="main" >
  <div >
    <div id="header"><img style="padding-top:5px;" alt="about" src="/images/about.png" width="426" height="230" border="0" usemap="#Map2" />
      <map name="Map2" id="Map2">
        <area shape="rect" coords="280,2,430,210" href="/about" alt="about" />
      </map>
    </div>
    <div  style="padding-right:26px;"> <?php echo $this->getChildHtml('global_messages') ?> <?php echo $this->getChildHtml('content') ?>
      <p align="justify" class="style1"><br />
      </p>
      <p class="style1"></p>
    </div>
  </div>
</div>
<script type="text/javascript">
$j(document).ready(function() {
    $j('.rotator').cycle({
		fx: 'fade', 
		speed:3000,
		timeout:9000  
	});
});

var iii = new Array();
<?php $i=1;
$_proCollection = Mage::getResourceModel('catalog/product_collection');
foreach ($_proCollection AS $f_product)
{
$cur_fproduct = Mage::getModel('catalog/product')->load($f_product->getId());
echo 'iii['.$i++.']="'.$this->helper('catalog/image')->init($cur_fproduct, 'thumbnail')->resize(100).'";
';	
}
 ?>
document.getElementById("sss").src=iii[4];
document.getElementById("sss2").src=iii[8];
// <![CDATA[
var ii=0;
function randomImage(){
if(ii==4){ ii=1; }else{ ii++;};
document.getElementById("sss").src=iii[ii];
}
var jjj=4;
function randomImage2(){
if(jjj==8){ jjj=5;}else{ jjj++;};
document.getElementById("sss2").src=iii[jjj];
}
// ]]>
</script>

<div class="rotator" id="bgimgdiv"> 
<img src="/images/backgrounds/retouched-2.jpg" alt=""  class="source-image"/>
<img src="/images/backgrounds/retouched-4.jpg" alt=""  class="source-image"/>
<img src="/images/backgrounds/retouched-1.jpg" alt=""  class="source-image"/>
<img src="/skin/frontend/default/default/images/images/backgrounds/voschk.jpg" alt="vos" class="source-image"/> 
</div>

<?php include_once('images/footer.php'); ?>

</body></html>
